### ISSUE TITLE
High false-positive in Inference

### ISSUE THREAD

**Issue by lukeb88** [krasserm/face-recognition#7]
I've adapted the code to work in real-time, capturing frames from a webcam.
Instead of test the accuracy on 10 different identities of the LFW i've tested against a subset of approximately 600 identities.

The results seem to be exaggeratedly good, the accuracy at threshold 0.43 is 0.99!!
![capture](https://user-images.githubusercontent.com/9743132/41150562-9d7d8f92-6b0e-11e8-91cc-bd0e21d1ba3c.PNG)

It can be a problem of overfitting? But it's strange, because the model is trained with FaceScrub and CASIA-WebFace when the test is done with LFW instead.

In addition to this, I would have another problem, in real-time: almost always the positive cases are predicted rightly, but I have a very high rate of false positives.

I've used, as suggested, a SVC for predict the class and then if the L2 distance between (at least) one of the embeddings of the class found and the embedding of the real-time frame is less the threshold, for me is the same face.

P.S. this isn't an issue with the code obviously, hope that you can help me anyway!

**Comment by krasserm** [comment]
You have to put accuracy in context. For example when you have a dataset with 1% positive pairs and 99% negative pairs and use a predictor that always predicts *different identity* you'll get an accuracy of 99%. This is an example of a *skewed class* problem i.e. one class (negative pairs) has much more members than the other class (positive pairs). In this case, accuracy is not a useful metric and the F1 score is much more significant. In your case the F1 score is a bit less than 0.6 which is not a good score for a classifier.

Furthermore, with the `nn4_small2_pretrained` model used in the blog post you are not able to achieve a good separation of the distance distributions of positive pairs and negative pairs. For example, the following histogram was generated with the `nn4_small2_pretrained` model and a subset of the data (i.e. face pairs) used in the blog post.

![histogram](https://user-images.githubusercontent.com/202907/41153928-99dbcf70-6b18-11e8-883c-6379acf83889.png)

You can see that the distance distributions of positive and negative pairs significantly overlap. This high overlap correlates with low F1 scores, both in your example as well as in the blog post. You see a high false-positive rate because there's a significant fraction of negative pair distances below the threshold. 

On the other hand, if you plot the distance distributions with a much bigger model, for example https://github.com/davidsandberg/facenet, you'll see that they are much better separated (almost perfectly). I cannot share that figure as I generated it in a commercial, confidential context. 

The model used in the blog post is more a toy model. If you want to have reasonable face recognition performance use https://github.com/davidsandberg/facenet or some of the other bigger public models.

Hope that helps.

**Comment by lukeb88** [comment]
Thank you for your very comprehensive reply. Now it's much clearer! 
You helped me a lot.

**Comment by krasserm** [comment]
You're welcome. Glad I could help.
